apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-example
  labels:
    app: front-end
spec:
  replicas: 2 # two pod will be created.
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: containerxyz
        image: nginx:latest #this image will be brought from docker hub
        ports:
        - containerPort: 80
